// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalApi.Models;

[Index("Riid", Name = "RentID_InvID", IsUnique = true)]
public partial class Invoice
{
    [Key]
    [Column("InvoiceID")]
    [StringLength(6)]
    [Unicode(false)]
    public string InvoiceId { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InvoiceDate { get; set; }

    [Column("RIID")]
    [StringLength(6)]
    [Unicode(false)]
    public string Riid { get; set; }

    [InverseProperty("Ip")]
    public virtual Payment Payment { get; set; }

    [ForeignKey("Riid")]
    [InverseProperty("Invoice")]
    public virtual Rental Ri { get; set; }
}