// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalApi.Models;

[Index("Ipid", Name = "InvID_PayID", IsUnique = true)]
public partial class Payment
{
    [Key]
    [Column("PaymentID")]
    [StringLength(6)]
    [Unicode(false)]
    public string PaymentId { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [Column("IPID")]
    [StringLength(6)]
    [Unicode(false)]
    public string Ipid { get; set; }

    [ForeignKey("Ipid")]
    [InverseProperty("Payment")]
    public virtual Invoice Ip { get; set; }
}