// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleRentalApi.Models;

public partial class Payment
{
    public string PaymentId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string Ipid { get; set; }

    public virtual Invoice Ip { get; set; }
}