// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalApi.Models;

public partial class Rental
{
    [Key]
    [Column("RentalID")]
    [StringLength(6)]
    [Unicode(false)]
    public string RentalId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RendalDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReturnDate { get; set; }

    [Required]
    [StringLength(10)]
    public string Status { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [Column("VehicleID")]
    [StringLength(6)]
    [Unicode(false)]
    public string VehicleId { get; set; }

    [InverseProperty("Ri")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("VehicleId")]
    [InverseProperty("Rentals")]
    public virtual Vehicle Vehicle { get; set; }

    [ForeignKey("RentalId")]
    [InverseProperty("Rentals")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}