// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleRentalApi.Models;

public partial class Vehicle
{
    public string VehicleId { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public DateOnly? Year { get; set; }

    public decimal? RentalPrice { get; set; }

    public bool? AvailabilityStatus { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}