// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VehicleRentalApi.Models;

public partial class Vehicle
{
    [Key]
    [Column("VehicleID")]
    [StringLength(6)]
    [Unicode(false)]
    public string VehicleId { get; set; }

    [Required]
    [StringLength(50)]
    public string Make { get; set; }

    [Required]
    [StringLength(50)]
    public string Model { get; set; }

    public DateOnly? Year { get; set; }

    [Column(TypeName = "money")]
    public decimal? RentalPrice { get; set; }

    public bool? AvailabilityStatus { get; set; }

    [InverseProperty("Vehicle")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}